//! The development-defaults `host.toml` for a bare `.wasm` (Manager §00.13,
//! "Resolving `--config`").
//!
//! CLNH-13 makes an absent required key a startup error, so `cln run` must
//! always supply a config — including for a component that arrived with none.
//! `cln run app.wasm` is meant to work without the developer authoring
//! configuration, so manager writes one into the run cache.
//!
//! **Generated configuration is development-only.** §00.13 is explicit that it
//! never sets `deployment-mode` to anything but `development`, so a reference
//! backend cannot silently become a production dependency. That is the one
//! value in here that is not a convenience.
//!
//! **This is not manager reimplementing the framework's generator.** The
//! framework's `dist/host.toml` is derived from project state — a guest's
//! imports decide its `[bridges]` block (FRM-BO-12), which requires reading the
//! component. Manager reads no wasm. What it writes here is the fixed minimum
//! CLNH-13 demands for a component that declares no capabilities, which is the
//! only kind of bare component that can run without one.

use std::path::{Path, PathBuf};

/// The world assumed for a bare component when the user names none.
///
/// `cli` is the only defensible default: it is the world whose host needs no
/// listener, no assets, and no deployment values, so its generated config is
/// complete. A server component needs a bind address that manager would have
/// to invent, and inventing one is how a development default becomes a
/// production surprise.
pub const DEFAULT_WORLD: &str = "cli";

/// Map a world to the host name and guest world that `clean-host-core`
/// expects in `[host] name` and `[guest] world`.
///
/// The guest world is not the same string as the `--world` flag: `--world=cli`
/// selects the `clean-cli` host, which implements the `cli-default` world.
pub fn host_and_guest_world(world: &str) -> (String, String) {
    // The host name is `clean-<world>` for every world the taxonomy defines,
    // and the guest world is that host's default handler. Deriving both rather
    // than matching means an unknown world produces a config the runtime can
    // reject by name — manager substituting a host it recognized would fail for
    // the wrong stated reason.
    (format!("clean-{world}"), format!("{world}-default"))
}

/// Render the development `host.toml` for a bare component.
///
/// `wasm_relative` is the component's path *as the host will resolve it* —
/// relative to this config file's own directory, which is how
/// `clean-host-core` reads `[guest] wasm`.
pub fn render(name: &str, world: &str, wasm_relative: &str) -> String {
    let (host, guest_world) = host_and_guest_world(world);

    format!(
        "# GENERATED by `cln run` for a bare component. Do not edit.\n\
         #\n\
         # This file exists because CLNH-13 makes a missing configuration a\n\
         # startup error, and a bare `.wasm` carries none. It is development\n\
         # configuration and is rewritten on every run.\n\
         #\n\
         # `deployment-mode` is fixed at \"development\" (Manager §00.13): a\n\
         # generated config must never let a reference backend become a\n\
         # production dependency.\n\
         \n\
         [host]\n\
         name            = \"{host}\"\n\
         version         = \"0.1.0\"\n\
         component-model = \"0.3.0\"\n\
         deployment-mode = \"development\"\n\
         \n\
         [guest]\n\
         name  = \"{name}\"\n\
         wasm  = \"{wasm_relative}\"\n\
         world = \"{guest_world}\"\n"
    )
}

/// Write the generated config into a run-cache directory, beside nothing else.
///
/// The config is written at `<dir>/host.toml` and points at the component with
/// a path relative to `dir`. Unlike a bundle — where the archive's own
/// `config/host.toml` sits one level down and reaches the component with
/// `../app.wasm` — here manager chooses both locations, so the two sit side by
/// side and the relative path is a bare file name.
pub fn write(dir: &Path, name: &str, world: &str, wasm: &Path) -> std::io::Result<PathBuf> {
    std::fs::create_dir_all(dir)?;

    // Prefer a relative path when the component is inside the cache directory,
    // and fall back to the absolute one when the user's `.wasm` lives
    // elsewhere — which is the normal case, since manager does not copy it.
    let wasm_ref = match wasm.strip_prefix(dir) {
        Ok(rel) => rel.to_string_lossy().into_owned(),
        Err(_) => wasm.to_string_lossy().into_owned(),
    };

    let path = dir.join("host.toml");
    std::fs::write(&path, render(name, world, &wasm_ref))?;
    Ok(path)
}

/// The guest name to use for a bare component: its file stem, which is the
/// only name available without reading the wasm.
pub fn name_for(wasm: &Path) -> String {
    wasm.file_stem()
        .map(|s| s.to_string_lossy().into_owned())
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| "component".into())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    fn parsed(text: &str) -> toml::Value {
        toml::from_str(text).expect("generated host.toml must be valid TOML")
    }

    #[test]
    fn the_generated_config_is_valid_toml_with_the_required_keys() {
        let v = parsed(&render("demo", "cli", "demo.wasm"));

        // The three keys CLNH-13 requires; an absent one is a startup error.
        for key in ["name", "version", "component-model"] {
            assert!(v["host"].get(key).is_some(), "[host] {key} is required");
        }
        assert_eq!(v["guest"]["wasm"].as_str(), Some("demo.wasm"));
        assert_eq!(v["guest"]["name"].as_str(), Some("demo"));
    }

    /// The one value in a generated config that is not a convenience.
    #[test]
    fn deployment_mode_is_always_development() {
        for world in ["cli", "server", "worker"] {
            let v = parsed(&render("demo", world, "demo.wasm"));
            assert_eq!(
                v["host"]["deployment-mode"].as_str(),
                Some("development"),
                "a generated config must never declare a non-development mode"
            );
        }
    }

    /// `--world=cli` selects the `clean-cli` host, whose world is
    /// `cli-default`. Writing `cli` into `[guest] world` would be refused by
    /// the host.
    #[test]
    fn the_cli_world_maps_to_the_hosts_default_world() {
        let v = parsed(&render("demo", "cli", "demo.wasm"));
        assert_eq!(v["host"]["name"].as_str(), Some("clean-cli"));
        assert_eq!(v["guest"]["world"].as_str(), Some("cli-default"));
    }

    #[test]
    fn the_server_world_maps_to_the_server_host() {
        let v = parsed(&render("demo", "server", "demo.wasm"));
        assert_eq!(v["host"]["name"].as_str(), Some("clean-server"));
    }

    #[test]
    fn writing_places_the_config_beside_the_component_reference() {
        let tmp = tempdir().unwrap();
        let dir = tmp.path().join("run/abc");
        let wasm = dir.join("app.wasm");
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(&wasm, b"\0asm").unwrap();

        let config = write(&dir, "app", "cli", &wasm).unwrap();
        let v = parsed(&std::fs::read_to_string(&config).unwrap());

        assert_eq!(config, dir.join("host.toml"));
        assert_eq!(
            v["guest"]["wasm"].as_str(),
            Some("app.wasm"),
            "a component inside the cache dir is referenced relatively"
        );
    }

    /// The normal case: the user's `.wasm` is somewhere else entirely and is
    /// not copied, so the reference has to be absolute.
    #[test]
    fn a_component_outside_the_cache_directory_is_referenced_absolutely() {
        let tmp = tempdir().unwrap();
        let dir = tmp.path().join("run/abc");
        let wasm = tmp.path().join("elsewhere/app.wasm");
        std::fs::create_dir_all(wasm.parent().unwrap()).unwrap();
        std::fs::write(&wasm, b"\0asm").unwrap();

        let config = write(&dir, "app", "cli", &wasm).unwrap();
        let v = parsed(&std::fs::read_to_string(&config).unwrap());

        assert_eq!(v["guest"]["wasm"].as_str(), Some(wasm.to_str().unwrap()));
    }

    #[test]
    fn the_guest_name_comes_from_the_file_stem() {
        assert_eq!(name_for(Path::new("/tmp/hello-world.wasm")), "hello-world");
        assert_eq!(name_for(Path::new("app.wasm")), "app");
    }

    #[test]
    fn a_nameless_path_still_yields_a_name() {
        assert_eq!(name_for(Path::new("/")), "component");
    }

    /// A regenerated config must not accumulate: writing twice leaves one file
    /// with current contents.
    #[test]
    fn writing_twice_overwrites_rather_than_appends() {
        let tmp = tempdir().unwrap();
        let dir = tmp.path().join("run/abc");
        let wasm = dir.join("app.wasm");
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(&wasm, b"\0asm").unwrap();

        write(&dir, "app", "cli", &wasm).unwrap();
        let second = write(&dir, "app", "cli", &wasm).unwrap();
        let text = std::fs::read_to_string(&second).unwrap();

        assert_eq!(text.matches("[host]").count(), 1);
    }
}
